import Head from "next/head";
import Container from "../components/Container";
import { Header, Footer, Main } from "../sections";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

 <Container>
     <Header />
     <Main/>
     <Footer/>
 </Container>
      
    </div>
  );
}
